myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('onlinecourse/', include('onlinecourse.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'onlinecourse'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path(route='', view=views.CourseListView.as_view(), name='index'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    # ex: /onlinecourse/5/
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    # ex: /enroll/5/
    path('<int:course_id>/enroll/', views.enroll, name='enroll'),

    # <HINT> Create a route for submit view

    # <HINT> Create a route for show_exam_result view

 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/models.py
import sys
from django.utils.timezone import now
from datetime import datetime
from datetime import date
from django.utils.translation import gettext_lazy as _

try:
    from django.db import models
except Exception:
    print("There was an error loading django modules. Do you have django installed?")
    sys.exit()

from django.conf import settings
import uuid
from model_utils import FieldTracker
from django.utils.timezone import now as djnow

Account = settings.AUTH_USER_MODEL


# Instructor model
class Instructor(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()

    created_date = models.DateField(default=date.today,
                                    help_text=_('Ngày chỉnh sửa gần nhất'),
                                    )

    updated_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ chỉnh sửa gần nhất'),
                                      )
    created_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ được tạo, không thể sửa đổi'),
                                      editable=False)
    tracker = FieldTracker()

    def __str__(self):
        return self.user.username


# Learner model
class Learner(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    STUDENT = 'student'
    DEVELOPER = 'developer'
    DATA_SCIENTIST = 'data_scientist'
    DATABASE_ADMIN = 'dba'
    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    social_link = models.URLField(max_length=200)

    created_date = models.DateField(default=date.today,
                                    help_text=_('Ngày chỉnh sửa gần nhất'),
                                    )

    updated_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ chỉnh sửa gần nhất'),
                                      )
    created_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ được tạo, không thể sửa đổi'),
                                      editable=False)
    tracker = FieldTracker()

    def __str__(self):
        return self.user.username + "," + \
               self.occupation


# Course model
class Course(models.Model):
    name = models.CharField(null=False, max_length=30, default='online course')
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Enrollment')
    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False
    grade = models.IntegerField(default=80,
                                null=True,
                                blank=True)
    created_date = models.DateField(default=date.today,
                                    help_text=_('Ngày chỉnh sửa gần nhất'),
                                    )

    updated_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ chỉnh sửa gần nhất'),
                                      )
    created_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ được tạo, không thể sửa đổi'),
                                      editable=False)

    tracker = FieldTracker()

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description

    def all_questions(self):
        return Question.objects.filter(course=self)


# Lesson model
class Lesson(models.Model):
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()
    created_by = models.ForeignKey(Account,
                                   on_delete=models.SET_DEFAULT,
                                   default=None,
                                   null=True,
                                   blank=True,
                                   related_name='%(app_label)s_%(class)s_created_by')
    updated_by = models.ForeignKey(Account,
                                   on_delete=models.SET_DEFAULT,
                                   default=None,
                                   null=True,
                                   blank=True,
                                   related_name='%(app_label)s_%(class)s_modified_by')
    created_date = models.DateField(default=date.today,
                                    help_text=_('Ngày chỉnh sửa gần nhất'),
                                    )

    updated_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ chỉnh sửa gần nhất'),
                                      )
    created_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ được tạo, không thể sửa đổi'),
                                      editable=False)
    tracker = FieldTracker()

    def __str__(self):
        return self.title


# Enrollment model
# <HINT> Once a user enrolled a class, an enrollment entry should be created between the user and course
# And we could use the enrollment to track information such as exam submissions
class Enrollment(models.Model):
    AUDIT = 'audit'
    HONOR = 'honor'
    BETA = 'BETA'
    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
        (BETA, 'BETA')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)

    created_date = models.DateField(default=date.today,
                                    help_text=_('Ngày chỉnh sửa gần nhất'),
                                    )

    updated_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ chỉnh sửa gần nhất'),
                                      )
    created_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ được tạo, không thể sửa đổi'),
                                      editable=False)
    tracker = FieldTracker()

    def __str__(self):
        return str(f"[{self.user.username}] - {self.course.name}")

    def questions(self):
        return self.course.all_questions()


class Question(models.Model):
    question_text = models.TextField(null=False,
                                     default="",
                                     blank=True)
    lesson = models.ForeignKey(Lesson,
                               null=True,
                               blank=True,
                               on_delete=models.CASCADE)
    course = models.ForeignKey(Course,
                               null=True,
                               blank=True,
                               on_delete=models.CASCADE)
    # choice_set = models.ManyToManyField(Choice,
    #                                     blank=True)
    # grade = models.CharField(default="0",
    #                          max_length=2048,
    #                          null=True,
    #                          blank=True)
    grade = models.IntegerField(default=1,
                                null=True,
                                blank=True)
    created_by = models.ForeignKey(Account,
                                   on_delete=models.SET_DEFAULT,
                                   default=None,
                                   null=True,
                                   blank=True,
                                   related_name='%(app_label)s_%(class)s_created_by')
    updated_by = models.ForeignKey(Account,
                                   on_delete=models.SET_DEFAULT,
                                   default=None,
                                   null=True,
                                   blank=True,
                                   related_name='%(app_label)s_%(class)s_modified_by')
    created_date = models.DateField(default=date.today,
                                    help_text=_('Ngày chỉnh sửa gần nhất'),
                                    )

    updated_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ chỉnh sửa gần nhất'),
                                      )
    created_at = models.DateTimeField(default=djnow,
                                      help_text=_('Ngày giờ được tạo, không thể sửa đổi'),
                                      editable=False)
    choices = []
    tracker = FieldTracker()

    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(is_correct=True).count()
        selected_correct = self.choice_set.filter(is_correct=True, id__in=selected_ids).count()
        if all_answers == selected_correct:
            return True
        else:
            return False

    def all_choices(self):
        return Choice.objects.filter(question=self)

    def correct_choices(self):
        return Choice.objects.filter(question=self, is_correct=True)

    # <HINT> A sample model method to calculate if learner get the score of the question
    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(is_correct=True).count()

onlinecourse/templates/onlinecourse/course_detail_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    <div class="container-fluid row">
        <div class="col-6">
            <h2>{{ course.name }}</h2>
                <div class="card-columns-vertical">
                    {% for lesson in course.lesson_set.all %}
                        <div class="card mt-1">
                            <div class="card-header"><h5>Lesson {{lesson.order|add:1}}: {{lesson.title}}</h5></div>
                            <div class="card-body">{{lesson.content}}</div>
                        </div>
                    {% endfor %}
                </div>
                <!-- Task: show questions and choices -->
                <!-- <HINT> Use Bootstrap Collapse to hide exam first, more details could be found here
                https://www.w3schools.com/bootstrap4/bootstrap_collapse.asp-->

                <!--
                A collapse example here:
                <div id="exam" class="collapse">
                    Click to expand elements within the collapse div
                    </div>
                -->


                <!--Check here to see more details Bootstrap checkbox
                 https://www.w3schools.com/bootstrap4/bootstrap_forms_inputs.asp-->
        </div>
        <div class="col-6">
                        <!-- <HINT> If user is authenticated, show course exam with a list of question -->
            {% if user.is_authenticated %}
                    <!-- A choice submission form example
                    <form id="questionform" action="point to a submit view" method="post">
                                ... for each question in the course ...
                                <div class="card mt-1">
                                    <div class="card-header"><h5>{{ question.question_text}}</h5></div>
                                    {% csrf_token %}
                                    <div class="form-group">
                                       ... for each choice in the question ...
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input type="checkbox" name="choice_{{choice.id}}"
                                                       class="form-check-input" id="{{choice.id}}"
                                                       value="{{choice.id}}">{{ choice.choice_text }}
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            <input class="btn btn-success btn-block" type="submit" value="Submit">
                    </form> -->
                <div class="card" data-toggle="collapse" href="#examCollapseId">
                    <div class="card-header">
                    <b>Start Exam</b>
                    </div>
                </div>
                <div id="examCollapseId" class="collapse">
                    <form id="questionform" action="{% url 'onlinecourse:submit' course_id=course.id %}" method="post">
                        {% for question in course.all_questions %}
                                <div class="card mt-1">
                                    <div class="card-header"><h5>{{ question.question_text}}</h5></div>
                                    {% csrf_token %}
                                    {% for choice in question.all_choices %}
                                    <div class="form-group">
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input type="checkbox" name="choice_{{choice.id}}_{{ question.id }}"
                                                       class="form-check-input" id="{{choice.id}}"
                                                       value="{{choice.id}}">{{ choice.choice_text }}
                                            </label>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                        {% endfor %}
                            <input class="btn btn-success btn-block" type="submit" value="Submit">
                    </form>
                </div>
            {% endif %}
        </div>

    </div>
</body>
</html>

onlinecourse/templates/onlinecourse/course_list_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Online Courses</title>
</head>
<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="#">Online Course</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    {% if course_list %}
        <div class="container">
            <div class="card-deck">
                {% for course in course_list %}
                         <div class="card" style="width: 36rem;">
                          <img class="card-img-left" src="{{MEDIA_URL}}/{{ course.image }}" width="240px" height="240px"
                               alt="Course image">
                          <div class="card-body bg-light">
                              <h5 class="card-title">{{ course.name }}, <span class="text-success">
                                  {{ course.total_enrollment}} enrolled</span></h5>
                            <p class="card-text">{{ course.description}}</p>
                            <form action="{% url 'onlinecourse:enroll' course.id %}" method="post">
                                  {% csrf_token %}
                                  <input class="btn btn-primary"  type="submit"
                                         value="{% if course.is_enrolled %}Enter{% else %}Enroll{% endif %} ">
                            </form>
                          </div>
                        </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>No courses are available.</p>
    {% endif %}
</body>
</html>

onlinecourse/templates/onlinecourse/exam_result_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

 <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Username" name="username" >
                        <input type="password" class="form-control" placeholder="Username" name="psw" >
                        <button class="btn btn-primary" type="submit">Login</button>
                        <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                    </div>
                </form>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid">
    {% if submission.get_grade > 0.8 %}
    <div class="alert alert-success">
       <!--HINT Display passed info -->
            <div>Congrate {{ user.username }}, you have passed exam with {{ submission.get_mark }}/{{ submission.count_questions }}</div>
    </div>
        {% else %}
        <div class="alert alert-danger">
            <!--HINT Display failed info -->
        <div>Failed! Sorry {{ user.username }}, you have failed exam with {{ submission.get_mark }}/{{ submission.count_questions }}</div>
        </div>
        <a class="btn btn-link text-danger" href="{% url 'onlinecourse:course_details' course.id %}">Re-test</a>
        {% endif %}
        <div class="card-columns-vertical mt-1">
        <h5 class="">Exam results</h5>
            <!--HINT Display exam results-->
            {% for choice_answer in submission.choices_answers %}
                <div class="card">
                    <div class="card-header">choice_answer.question.question_text</div>
                    <div class="card-body">
                        <div>Correct answer:
                            {% for a in choice_answer.question.correct_choices %}
                            <li>{{ a.choice_text }}</li>
                            {% endfor %}
                        </div>
                        <div>Your answer:
                            {% for a in choice_answer.all_choices %}
                                <li>{{ a.choice_text }}</li>
                                {% endfor %}
                                </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

onlinecourse/templates/onlinecourse/user_login_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Login form -->
    <form action="{% url 'onlinecourse:login' %}" method="post">
        {% csrf_token %}
        <div class="container"> <!--Style root div with .container class -->
            <h1>Login</h1>
            <div class="form-group"> <!--Style second div with .form-group class -->
              <label for="username"><b>User Name</b></label>
              <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
              <label for="psw"><b>Password</b></label>
              <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
            </div>
            {% if message %}
              <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                {{ message }}
              </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Login</button> <!--Style button with .btn and .btn-primary class -->
        </div>
    </form>

</body>

onlinecourse/templates/onlinecourse/user_registration_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Registration form -->
    <form action="{% url 'onlinecourse:registration' %}" method="post">
        <div class="container"> <!--Style root div with .container class -->
            {% csrf_token %}
            <h1>Sign Up</h1>
            <hr>
            <div class="form-group"> <!--Style second div with .form-group class -->
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
                {% if message %}
                <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                    {{ message }}
                </div>
                {% endif %}
                <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
            </div>
        </div>
    </form>

</body>